# fmake does not need a build system, and this is not one. It exists so that
# `make install` and `make deb` mean what everyone expects them to, and so
# debhelper has the target it looks for. The program is a single script; all
# `install` does is copy it and its manual page into place.

PREFIX  ?= /usr/local
DESTDIR ?=

# Where build products land. dpkg-buildpackage writes to the parent
# directory, which is not this build's to write to: with two of these
# projects side by side in ~/src, `make deb` in one drops files into the
# directory holding the other. They are moved here afterwards, which also
# lets clean name them.
BUILD_DIR  ?= build

# Read rather than restated. Two hand-edited copies of a version number
# drift, and the symptom is a package whose reported version disagrees with
# the one that installed it.
VERSION     = $(shell sed -n 's/^VERSION *= *"\(.*\)"/\1/p' fmake)
DEB_VERSION = $(shell sed -n '1s/^[^(]*(\([^)]*\)).*/\1/p' debian/changelog)
DEB_ARCH    = $(shell dpkg-architecture -qDEB_HOST_ARCH 2>/dev/null)

DEB         = $(BUILD_DIR)/fmake_$(VERSION)_all.deb
DEB_EXTRA   = $(BUILD_DIR)/fmake_$(VERSION)_$(DEB_ARCH).buildinfo \
              $(BUILD_DIR)/fmake_$(VERSION)_$(DEB_ARCH).changes

# The interpreter written into the installed copy. Debian Policy 10.4 wants
# an absolute path, and every packaged Python script on a Debian system has
# one. The file in the repository keeps /usr/bin/env, because copying it
# into $PATH and running it anywhere is the other half of what fmake is, and
# that half wants the lookup.
PYTHON  ?= /usr/bin/env python3

BINDIR  = $(DESTDIR)$(PREFIX)/bin
MANDIR  = $(DESTDIR)$(PREFIX)/share/man/man1

.PHONY: all install uninstall check check-version deb lint clean test veryclean distclean style style-source style-docs

all: fmake.1

# Generated by fmake itself, so the option list cannot drift from the one
# argparse accepts.
fmake.1: fmake
	./fmake --man > $@

install: fmake.1
	install -d $(BINDIR) $(MANDIR)
	sed '1s|^#!.*|#!$(PYTHON)|' fmake > $(BINDIR)/fmake
	chmod 755 $(BINDIR)/fmake
	install -m 644 fmake.1 $(MANDIR)/fmake.1

uninstall:
	rm -f $(BINDIR)/fmake $(MANDIR)/fmake.1

check: check-version style test

# The version is written in two files and nothing else compares them. This
# is what debian/rules runs in place of the suite: it needs no compiler, so
# the package build itself refuses to produce a mismatched pair.
check-version:
	@test -n "$(VERSION)" || { echo "no VERSION in fmake" >&2; exit 1; }
	@test -n "$(DEB_VERSION)" || { echo "no version in debian/changelog" >&2; exit 1; }
	@test "$(VERSION)" = "$(DEB_VERSION)" || { \
		echo "version mismatch: fmake says $(VERSION), debian/changelog says $(DEB_VERSION)" >&2; \
		exit 1; }

# Builds ../fmake_<version>_all.deb. -b because there is no upstream tarball
# to sign or ship: the packaging is native and the source is this directory.
deb: lint

# Separated so `make lint` works on a package already built, and skipped
# rather than fatal when lintian is absent -- it is a checker, not a
# dependency of producing the thing.
lint:
	dpkg-buildpackage -b -us -uc
	@mkdir -p $(BUILD_DIR)
	@for f in fmake_$(VERSION)_all.deb \
	          fmake_$(VERSION)_$(DEB_ARCH).buildinfo \
	          fmake_$(VERSION)_$(DEB_ARCH).changes; do \
		if [ -e "../$$f" ]; then mv -f "../$$f" $(BUILD_DIR)/; fi; \
	done
	@test -f $(DEB) || { echo "deb: $(DEB) was not produced" >&2; exit 1; }
	@echo
	@if command -v lintian >/dev/null; then \
		lintian --pedantic $(DEB) && echo "lintian: clean"; \
	else \
		echo "lintian not installed; package not checked"; \
	fi
	@echo $(DEB)

# Named targets only, and no wildcard sweeps: a clean target is the one
# thing everybody runs without reading. The two directories are debhelper's
# own staging trees -- created by the build, relative, and named outright.
clean:
	rm -f fmake.1 debian/files debian/debhelper-build-stamp \
	      debian/fmake.substvars debian/fmake.debhelper.log \
	      $(DEB) $(DEB_EXTRA)
	rm -rf debian/fmake debian/.debhelper
	@rmdir $(BUILD_DIR) 2>/dev/null || :

# The shared style gate: one tool, copied verbatim from
# ~/.claude/tools/style_gate.py into every private project. It refuses to
# run against a collapsed file list, so a pass means it actually looked.
style: style-source style-docs

style-source:
	$(PYTHON) tools/style_gate.py check

# project.md is authoritative, so it is held to the tree: a heading
# that appears twice means whichever one you find, the other is the
# one with the answer.
style-docs:
	$(PYTHON) tools/style_gate.py docs

# `test` is the suite alone; `check` is everything that must pass first.
test:
	./selftest

# The clean ladder, matching the sibling projects.
veryclean: clean
	rm -rf $(BUILD_DIR)

distclean: veryclean
	find . -name '*~' -o -name '*.swp' -o -name '*.orig' | xargs -r rm -f
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
