# fmake does not need a build system, and this is not one. It exists so that
# `make install` and `make deb` mean what everyone expects them to, and so
# debhelper has the target it looks for. The program is a single script; all
# `install` does is copy it and its manual page into place.

PREFIX  ?= /usr/local
DESTDIR ?=

# The interpreter written into the installed copy. Debian Policy 10.4 wants
# an absolute path, and every packaged Python script on a Debian system has
# one. The file in the repository keeps /usr/bin/env, because copying it
# into $PATH and running it anywhere is the other half of what fmake is, and
# that half wants the lookup.
PYTHON  ?= /usr/bin/env python3

BINDIR  = $(DESTDIR)$(PREFIX)/bin
MANDIR  = $(DESTDIR)$(PREFIX)/share/man/man1

.PHONY: all install uninstall check deb lint clean

all: fmake.1

# Generated by fmake itself, so the option list cannot drift from the one
# argparse accepts.
fmake.1: fmake
	./fmake --man > $@

install: fmake.1
	install -d $(BINDIR) $(MANDIR)
	sed '1s|^#!.*|#!$(PYTHON)|' fmake > $(BINDIR)/fmake
	chmod 755 $(BINDIR)/fmake
	install -m 644 fmake.1 $(MANDIR)/fmake.1

uninstall:
	rm -f $(BINDIR)/fmake $(MANDIR)/fmake.1

check:
	./selftest

# Builds ../fmake_<version>_all.deb. -b because there is no upstream tarball
# to sign or ship: the packaging is native and the source is this directory.
deb: lint

# Separated so `make lint` works on a package already built, and skipped
# rather than fatal when lintian is absent -- it is a checker, not a
# dependency of producing the thing.
lint:
	dpkg-buildpackage -b -us -uc
	@echo
	@if command -v lintian >/dev/null; then \
		lintian --pedantic ../fmake_*_all.deb && echo "lintian: clean"; \
	else \
		echo "lintian not installed; package not checked"; \
	fi
	@ls -1 ../fmake_*_all.deb | tail -1

clean:
	rm -f fmake.1
	rm -rf debian/fmake debian/.debhelper debian/files \
	       debian/debhelper-build-stamp debian/*.substvars debian/*.debhelper.log
